added more options including verbose, notify, daemon

diff --git a/mpdnotify b/mpdnotify
--- a/mpdnotify
+++ b/mpdnotify
@@ -3,22 +3,59 @@
 MPDPID=$(pidof mpd)
 STATEFILE="$HOME/.config/mpd/state"
 
-mpd_notify() {
-    notify "MPD: $@"
+usage() {
+    echo "Usage: $(basename $0) [-h] [-d] [-nv]"
+    [ $VERBOSE ] && cat <<EOF
+    -h : print this help
+
+    -d : run in daemon mode
+
+    -n : notify using \`notify\`
+    -v : be more verbose
+EOF
+    exit 1
 }
 
-handle() {
+out() {
+    printf "MPD: %s\n" "$@"
+    [ $NOTIFY ] && notify "MPD: $@"
+}
+
+out_status() {
     status="$(mpc status | grep -o -e "playing\|paused")"
 
     case "$status" in
-        playing) mpd_notify "$(mpc current)" ;;
-         paused) mpd_notify "paused" ;;
-              *) mpd_notify "stopped" ;;
+        playing)
+            [ $VERBOSE ] && printf "Currently playing:\n"
+            out "$(mpc current)"
+            ;;
+        paused) 
+            out "paused" 
+            ;;
+        *) 
+            out "stopped"
+            ;;
     esac
 }
 
-test -z $MPDPID && printf "mpd not running\n" && exit 1
+run_daemon() {
+    [ $VERBOSE ] && printf "Starting mpdnotify in daemon mode.\n"
+    while read -r; do
+        out_status
+    done < <(mpc idleloop player)
+    [ $VERBOSE ] && printf "Stopped mpdnotify.\n"
 
-while read -r; do
-    handle
-done < <(mpc idleloop player)
+}
+
+[ ! $MPDPID ] && printf "Error: MPD is not running\n" && exit 1
+
+while getopts "hdvn" opt; do
+    case $opt in
+        d) DAEMON=true ;;
+        v) VERBOSE=true ;;
+        n) NOTIFY=true ;;
+        *) usage ;;
+    esac
+done
+
+[ $DAEMON ] && run_daemon || out_status
