nicer design

diff --git a/tmx b/tmx
--- a/tmx
+++ b/tmx
@@ -7,38 +7,36 @@ EOF
 }
 
 attach() {
-    tmux attach-session -t "$1" 2> /dev/null
+    tmux attach-session -t $SESSION_NAME 2> /dev/null
 }
 
-create_uni() {
-    SESSION_NAME="uni"
-    DIR="`curterm`"
-    
-    test -z $DIR && printf "Error loading dir\n" && exit 1
-
-    tmux new-session -d -n "misc" -s "$SESSION_NAME"
-
-    for d in `ls -d $DIR/*`; do
-        cd $d
-        tmux new-window -t "$SESSION_NAME" -n "$(basename $d)" -d
-    done
-
-    attach $SESSION_NAME
-}
-
-create_random() {
-    SESSION_NAME="random"
-
-    tmux new-session -d -n "music" -s $SESSION_NAME "ncmpcpp"
-    tmux split-window -v -p 33 -t $SESSION_NAME "cava"
-
-    tmux select-pane -U -t $SESSION_NAME
-
-    attach $SESSION_NAME
+create() {
+    case $SESSION_NAME in
+        uni)
+            DIR="`curterm`"
+            test -z $DIR && printf "Error loading dir\n" && exit 1
+            tmux new-session -d -n "misc" -s "$SESSION_NAME"
+            for d in `ls -d $DIR/*`; do
+                cd $d
+                tmux new-window -t "$SESSION_NAME" -n "$(basename $d)" -d
+            done
+            tmux kill-window -t $SESSION_NAME:misc
+            ;;
+        music)
+            tmux new-session -d -n "music" -s $SESSION_NAME "ncmpcpp"
+            tmux split-window -v -p 33 -t $SESSION_NAME "cava"
+            tmux select-pane -U -t $SESSION_NAME
+            tmux set-option -t $SESSION_NAME status off
+            ;;
+        *)
+            echo "No such session defined" > /dev/stderr
+    esac
 }
 
 case "$1" in
-    u*) attach $1 || create_uni ;;
-    r*) attach $1 || create_random ;;
+    u*) export SESSION_NAME="uni" ;;
+    m*) export SESSION_NAME="music" ;;
      *) usage ;;
 esac
+
+attach || ( create && attach )
